version: "~> 1.0"
language: node_js
os: linux
dist: focal
if: branch = "stable" OR tag IS present
jobs:
  include:
  - stage: Build project
    name: Build the project on Linux with NodeJS 14
    os: linux
    dist: focal
    node_js: '14'
    script: npx tsc
  - stage: Build project
    name: Build the project on Windows with NodeJS 14
    os: windows
    node_js: '14'
    script: npx tsc
  - stage: Release to NPM
    name: Publish the package to the npmjs repository
    os: linux
    dist: focal
    node_js: '14'
    script: npx tsc
    deploy:
      provider: npm
      email: npmjs@eraud.dev
      api_key:
        secure: 2Fuu65yuvjadxnAUcfj+r6JhCzFj+/pKv5NOApUXQXItc+ec47hsHAH1BaKLofgymNtPe3bJHIIaZLKUfv9kwyUIN8eRfS92GExjcsFprO0s0qCpZm2rmhs/mBKF1i2NuF2ONdwe6e1ntBtHKeLHFILtCQvcyi+PrsPVebk1fNWSuWks/4eaFaDgJM2D+DfViYAaNAkxYb5P7mQ0l19WmLDYufGh1W/2iuYaGAko/J0D7Velpee1lEmoyUk6Sf9n+kO16CXo3aNEoyUQUqwKRRrUajmlw+FIIm4yogmOvGH5gNuctRYGGwTTxIADLw3Q26ZiSsAww+m6sYIcprAhYVmHOnpNwiy51rxe9SBDJxJVk9nQGzONxmaqAj/5pIHT2UOi2BGU3v9QpU/mCFAQmtwY52V4l8Nz65YYy6+p/wZtTqan/H81n08clfkkHcMvdVUIHt39hwVN/CB5r2iC+eJbLz3LRhUiYfot9qvT87/SO67ovtmfPePBFy4uy7VLsIhzRCKj6xDt/fPHeyTXogQY7RzGTzWUw65NoAI09KN47FuxnDGB8yljg7hvFPjJrccMM9A2ddmgNV7BcrY1BzCLiGXjJagwYxd+7GDdc1MsJYmJK6NtXJ+xy80aXR7kbsDQvpYWB9vVOd6QmmA+hx0bVPuXrOMUB7DYNDfwlMY=
      on:
        tags: true
        repo: lesjoursfr/exifr-cli
        branch: stable
      cleanup: false
notifications:
  slack:
    secure: G/EmXHuyV5D4eSF2JJY3gF/0PEkGsMFOdU8UU5NArfYBa11K5kJpEpjOJr8wr3xK2sd+8lD/zSXxgnOuemF9SrNc7P2s3BlUjmWFKcU6NQQEmNF47Cy46D/3jW6mkXHPyR04zcfyWvOEYYRe0ziJ/vfnO4wNLa54RYkTw0mEJPnCFFXLCCN7znrTh0AtaKiTn4npxF201GISCHc2T6s9g7Fq3gQSFU+t4E4Wjq9Nbi59agHPxSfNp9h52E6a3dTsRgO59DCuhq/QQs61kjf6mBzDT9QTywhaqQHvK7DdLB5EO3p/gxwheVgDqFl+iz8WRQezIMzbnlkQmi9kcBn7H99EQii06uDVQ+YaV0m7anLoJs1NwIagJDO+es4wPplo3O3daoQRxrFOQ/WjWdQjUw2VTN+y1Zy3gh8HCxsiG6bo1KnSur0XGe+CI35tYcO5QTFJpltaNfrpABXMPuCVMl9Kv4KTiEeb7r8U2M0b1E2fiGyIfRPO6869n+2PYZCaCkWy6Sid0lPbGly0RReNz5xIud+cfcxkdavSSzvSY8BKX2DuZfrTi82ac7Qu/JgtQooA3QPmVHxRfWZAcYnB1dfIROAHc8G61Qa2534ycKgDHxyF6bQNM5yGaM8lz7wppsrEeepDsahgFp6hCl3p3kCEhOhI4BCAje9LvJ1thTI=
